/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package io.gatling.liferay.model.impl;

import aQute.bnd.annotation.ProviderType;

import io.gatling.liferay.model.FormParam;
import io.gatling.liferay.service.FormParamLocalServiceUtil;

/**
 * The extended model base implementation for the FormParam service. Represents a row in the &quot;StressTool_FormParam&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FormParamImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FormParamImpl
 * @see FormParam
 * @generated
 */
@ProviderType
public abstract class FormParamBaseImpl extends FormParamModelImpl
	implements FormParam {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a form param model instance should use the {@link FormParam} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			FormParamLocalServiceUtil.addFormParam(this);
		}
		else {
			FormParamLocalServiceUtil.updateFormParam(this);
		}
	}
}